
#ifndef BIBLIOS_H
#define BIBLIOS_H

#include <biblio.H>

extern BibEntry abedini_2010;

extern BibEntry ahmed_1989;

extern BibEntry ahmed_2010;

extern BibEntry ahmed_2016;

extern BibEntry alMarhoun_1988;

extern BibEntry alShammasi_1999;

extern BibEntry alShammasi_2001;

extern BibEntry banzer_1996;

extern BibEntry baker_1956;

extern BibEntry baker_2015;

extern BibEntry beal_1946;

extern BibEntry beggs_1973;

extern BibEntry beggs_1975;

extern BibEntry beggs_1987;

extern BibEntry brill_1974;

extern BibEntry brown_1948;

extern BibEntry carr_1954;

extern BibEntry cegarra_2007;

extern BibEntry chew_1959;

extern BibEntry culberson_1951;

extern BibEntry danesh_1998;

extern BibEntry dean_1958;

extern BibEntry deGhetto_1995;

extern BibEntry dempsey_1965;

extern BibEntry dindoruk_2004;

extern BibEntry dodson_1944;

extern BibEntry dokla_1992;

extern BibEntry dranchuk_1973;

extern BibEntry dranchuk_1975;

extern BibEntry elsharkawy_2000_1;

extern BibEntry elsharkawy_2000_2;

extern BibEntry fekete_2012;

extern BibEntry flowSimulation_2017;

extern BibEntry gawish_2005;

extern BibEntry glaso_1980;

extern BibEntry gopal_1977;

extern BibEntry guo_2014;

extern BibEntry hanafy_1997;

extern BibEntry hall_1973;

extern BibEntry jennings_1971;

extern BibEntry kareem_2016;

extern BibEntry kartoatmodjo_1991;

extern BibEntry kartoatmodjo_1994;

extern BibEntry kay_1936;

extern BibEntry kesler_1976;

extern BibEntry khan_1987;

extern BibEntry lasater_1958;

extern BibEntry lee_1966;

extern BibEntry liu_2017;

extern BibEntry liu_2017_2;

extern BibEntry lopez_2005;

extern BibEntry lopez_2014;

extern BibEntry manucci_1968;

extern BibEntry mao_2009;

extern BibEntry mapleTech_2017;

extern BibEntry mathews_1942;

extern BibEntry mattar_1975;

extern BibEntry matthews_1967;

extern BibEntry mcCain_1988;

extern BibEntry mcCain_1990;

extern BibEntry mcCain_1991;

extern BibEntry mcCain_2011;

extern BibEntry mcCoy_1983;

extern BibEntry meehan_1980;

extern BibEntry millan_1984;

extern BibEntry naseri_2005;

extern BibEntry numbere_1977;

extern BibEntry ng_1983;

extern BibEntry osif_1988;

extern BibEntry papay_1968;

extern BibEntry perez_2001;

extern BibEntry perez_2001_2;

extern BibEntry petrosky_1993;

extern BibEntry petrosky_1995;

extern BibEntry petroleumOffice_2016;

extern BibEntry petroleumOfficeUnitConverter_2017;

extern BibEntry petroWiki_2016;

extern BibEntry petroWiki_2016_2;

extern BibEntry petroWiki_2016_3;

extern BibEntry petroWiki_2016_4;

extern BibEntry petroWiki_2016_5;

extern BibEntry petroWiki_2016_6;

extern BibEntry petroWiki_2016_7;

extern BibEntry ramey_1964;

extern BibEntry salazar_2008;

extern BibEntry sarem_1961;

extern BibEntry sattarin_2007;

extern BibEntry spivey_2004;

extern BibEntry standing_1942;

extern BibEntry standing_1947;

extern BibEntry standing_1977;

extern BibEntry sutton_1985;

extern BibEntry takacs_1976;

extern BibEntry takacs_1989;

extern BibEntry takacs_2005;

extern BibEntry totalCFP_1983;

extern BibEntry vanWingen_1950;

extern BibEntry vazquez_1980;

extern BibEntry velarde_1997;

extern BibEntry wang_2009;

extern BibEntry whitson_1984;

extern BibEntry whitson_2000;

extern BibEntry wichert_1972;

extern BibEntry yarborough_1974;

#endif // BIBLIOS_H
