# coding: utf-8

begin_correlation("VeqspMcCain", "EquivalentVolume", "SCF_STB", 650, 4500)
add_title("CALCULATION OF EQUIVALENT VOLUME FOR TWO STAGES OF SEPARATION")
add_parameter("tsp1", "Fahrenheit", "Primary separator temperature", 60, 120)
add_parameter("psp1", "psia", "Primary separator pressure", 100, 700)
add_parameter("yg", "Sgg", "Primary separator gas gravity", 0.6, 0.8)
add_parameter("api", "Api", "API condensate gravity", 40, 70)
add_author("McCain (Primary Separator)")
add_note("Calculation of primary separator equivalent volume (for two stages of separation).")
add_note("The equivalent volume is the volume of stock-tank gas plus the volume in scf that would be occupied by a barrel of stock-tank liquid if it were gas.")
add_note("This equation is not recommended when the total nonhydrocarbon content of the gas exceeds 25 mol%.")
add_ref("mcCain:1991")
add_internal_note("The equation was verified by using the original reference: McCain (1991). Date: March 06 2017.")
set_hidden_blackoil_grid()
set_hidden_drygas_grid()
set_hidden_wetgas_grid()
end_correlation()

################################################################

begin_correlation("Veqsp2McCain", "EquivalentVolume", "SCF_STB", 550, 5000)
add_title("CALCULATION OF EQUIVALENT VOLUME FOR THREE STAGES OF SEPARATION")
add_parameter("tsp1", "Fahrenheit", "Primary separator temperature", 60, 120)
add_parameter("tsp2", "Fahrenheit", "Second separator temperature", 60, 120)
add_parameter("psp1", "psia", "Primary separator pressure", 100, 1500)
add_parameter("yg", "Sgg", "Primary separator gas gravity", 0.6, 0.8)
add_parameter("api", "Api", "API condensate gravity", 40, 70)
add_author("McCain (Second Separator)")
add_note("Calculation of second separator equivalent volume (for three stages of separation).")
add_note("The equivalent volume is the volume of stock-tank gas and second-separator gas, plus the volume in scf that would be occupied by a barrel of stock-tank liquid if it were gas.")
add_note("This equation is not recommended when the total nonhydrocarbon content of the gas exceeds 25 mol%.")
add_ref("mcCain:1991")
add_internal_note("The equation was verified by using the original reference: McCain (1991). Date: March 06 2017.")
set_hidden_blackoil_grid()
set_hidden_drygas_grid()
set_hidden_wetgas_grid()
end_correlation()
