# coding: utf-8
begin_correlation("BoaMcCain", "UndersaturatedOilFormationVolumeFactor", "RB_STB")
add_title("McCain CORRELATION, CALCULATION OF UNDERSATURATED OIL FORMATION VOLUME FACTOR")
add_db("Based on the equation presented by McCain (1990).")
add_db("The volume factor at bubble point pressure is adjusted to higher pressures through the use of the coefficient of isothermal compresibility.")
add_ref("banzer:1996") 
add_ref("mcCain:1990")                  
add_parameter("p", "psia", "Pressure")
add_parameter("pb", "psia", "Bubble point pressure")
add_synonym("bob", "RB_STB", "Oil formation volume factor at pb")
add_parameter("co", "psia_1", "Solution GOR")
add_author("McCain")
add_note("This correlation determines the oil formation volume factor for pressures above the bubble point pressure.")
add_note("The correlation was verified by using the original reference and Bánzer (1996) as a secondary reference. Date: October 26 2016")
end_correlation()
