# coding: utf-8

begin_correlation("YwgrMcCain", "WetGasSpecificGravity", "Sgg", 0.8, 1.55)
add_title("CALCULATION OF RESERVOIR WET GAS SPECIFIC GRAVITY")
add_parameter("ygsp1", "Sgg", "Primary separator gas gravity")
add_parameter("api", "Api", "API condensate gravity")
#add_parameter("ogrsp1", "STB_MMSCF", "Primary separator condensate gas ratio")
add_parameter("rsp1", "SCF_STB", "Primary separator producing GOR")
add_parameter("gpa", "SCF_STB", "Additional gas produced")
add_parameter("veq", "SCF_STB", "Equivalent volume")
add_author("McCain (Wet Gas Gravity Correction)")
add_note("Calculation of reservoir wet gas specific gravity.")
add_note("This equation is not recommended when the total nonhydrocarbon content of the gas exceeds 25 mol%.")
add_internal_note("Condensate gas ratio is the inverse of producing GOR, which is used by McCain (1991) to estimate the reservoir wet gas specific gravity.")
add_internal_note("The equation was verified by using the original reference: McCain (1991). Date: March 06 2017.")
add_ref("mcCain:1991")
end_correlation()
