
/**    \mainpage   

       # ZEN PVT library
    
       This the stunning ZEN PVT library.

       ## Architectural guidelines

       ### The target General Architecture

       - Scalable
       
       - Secure

       - Responsiveness

       - Resiliency

       ### The calculation engine library

       ### Command

       ## Correlation engine

       ## Tuning

       ## Back ends

       ### Computing correlations

       ### Tuning 

       ### Zfactor tuning

       ### Grid generation

       \ref Correlations

       \ref Tuning

 */ 

/** @defgroup Correlations Correlations

*/

/** @defgroup Tuning Tuning

 */
