#!/usr/bin/env ruby
# -*- coding: iso-8859-1 -*-

require 'optionparser'

load 'correlations.rb'

def test_preamble
%Q{
# include <cassert>
# include <correlations/correlation.H>

int main()
{
}
end


options = {}
options_parser = OptionParser.new do |opts|

  opts.on('-f NAME', '--file NAME', 
          'file name with correlation tests') do |file_name|
    options[:file_name] = file_name
  end

end

options_parser.parse!

file = options[:file_name]

fail 'correlations file not specified' if file.nil?

require 'csv'

rows = CSV.read(file, headers: true)

puts test_preamble
rows.each_with_index do |row, line|

  corr = $correlations_tbl[row[0]]
  fail "correlation #{row[0]} not found at line #{line + 1}" unless corr
  
  puts corr.name
  
end
