#!/usr/bin/env ruby
# -*- coding: iso-8859-1 -*-

file_name = ARGV.shift

puts file_name

def process_par(tokens)
  puts '================================================================'
  puts "tokens = = #{tokens}"
  if tokens.size == 2
    return "#{tokens.shift}, \"\"#{tokens}"
  end
  s = "#{tokens.shift},#{tokens.shift}, \"\""
  tokens.each do |t|
    s += ", #{t}"
  end
  puts s
end

lines = File.open(file_name).readlines

content = []
lines.each do |line|
  content << line unless line.include? 'add_parameter'
end



exit

File.open(file_name).each do |line|
  process_par(line) if line.include? 'add_parameter'
end
