#!/usr/bin/env ruby
# -*- coding: iso-8859-1 -*-

file_name = ARGV.shift

def process_par(line)
  tokens = line.split ','
  if tokens.size == 2
    s1 = tokens.shift
    s2 = tokens.shift
    s2.tr!(')', '').chomp!
    return "#{s1}, #{s2}, \"Aqui Neylith\")"
  end

  s = "#{tokens.shift},#{tokens.shift}, \"Aqui Neylith\""
  tokens.each do |t|
    s += ", #{t}"
  end
  s
end

lines = File.open(file_name).readlines

content = []
buffer = nil
lines.each do |line|
  if buffer
    buffer += line
    content << buffer.gsub(/\s+/, " ")
    buffer = nil
    next
  end
  
  if line.include? 'add_parameter' 
    if line =~ /\)\s*$/ # termina en ) seguido de cero o mas espacios ?
      content << line
      next
    end
    buffer = line.chomp
    next
  end
  content << line
end

content.each do |line|
  if line.include? 'add_parameter'
    puts process_par line
  else
    puts line
  end
end




