
begin_correlation("UgCarrKB", "GasViscosity", "CP")
add_title("CARR ET AL. CORRELATION, CALCULATION OF GAS VISCOSITY")
add_parameter("t", "Rankine", "Aqui Neylith",  "Quantity<Fahrenheit>(100)",  "Quantity<Fahrenheit>(300)") 
add_parameter("p",  "psia", "Aqui Neylith")
add_parameter("tsc",  "Rankine", "Aqui Neylith")
add_parameter("psc",  "psia", "Aqui Neylith")
add_parameter("yg", "Sgg", "Aqui Neylith",  0.55,  1.55)
add_parameter("n2_concentration",  "MolePercent", "Aqui Neylith")
add_parameter("co2_concentration",  "MolePercent", "Aqui Neylith")
add_parameter("h2s_concentration",  "MolePercent", "Aqui Neylith")
add_author("Carr et al.")
add_db("Carr et al. developed charts that are the most widely used for calculating the viscosity of natural gas from the pseudoreduced temperature and pressure.")
add_ref("carr:1954")
add_ref("dempsey:1965")
add_ref("standing:1977")
add_ref("banzer:1996")
add_ref("petroWiki:2016:2")
add_note("Carr et al. (1954) presented the graphs of the correlation. Dempsey (1965) expressed them in a mathematical form.")
add_note("A linear effect of concentration was assumed to apply over the concentration range from 0 to 15 mol percent of non-hydrocarbon components.")
add_internal_note("The equation was verified by using secondary references: Bánzer (1996) and Standing (1977). Date: September 29 2016.")
add_internal_note("The development ranges were presented by Bánzer (1996).")
add_internal_note("The description was obtained from PetroWiki.")
end_correlation()

################################################################

begin_correlation("UgLeeGE", "GasViscosity", "CP")
add_title("LEE ET AL. CORRELATION, CALCULATION OF GAS VISCOSITY")
add_parameter("t", "Rankine", "Aqui Neylith",  "Quantity<Fahrenheit>(100)",  "Quantity<Fahrenheit>(340)") 
add_parameter("p", "psia", "Aqui Neylith",  100,  8000)
add_parameter("yg",  "Sgg", "Aqui Neylith")
add_parameter("z",  "ZFactor", "Aqui Neylith")
add_author("Lee et al.")
add_ref("lee:1966")
add_ref("banzer:1996")
add_db("Based on experimental viscosity and density data of four natural gases. The samples were furnished by the Atlantic Richfield Co., the Continental Oil Co. and the Pan American Petroleum Corp.")
add_internal_note("The correlation was verified by using the original reference and a secondary one: Bánzer (1996). Date: October 03 2016.")
end_correlation()

################################################################

begin_correlation("UgDeanStiel", "GasViscosity", "CP")
add_title("DEAN & STIEL CORRELATION, CALCULATION OF GAS VISCOSITY")
add_author("Dean & Stiel")
add_parameter("t",  "Rankine", "Aqui Neylith")
add_parameter("p",  "psia", "Aqui Neylith")
add_parameter("tsc",  "Rankine", "Aqui Neylith")
add_parameter("psc",  "psia", "Aqui Neylith")
add_parameter("yg",  "Sgg", "Aqui Neylith")
add_parameter("z",  "ZFactor", "Aqui Neylith")
add_ref("dean:1958")
add_ref("gawish:1995")
add_internal_note("The original reference is not available. The correlation was verified by using a secondary reference: Gawish & Al-Homadhi (2005). Date: October 03 2016.")
end_correlation()
