begin_correlation("Pg", "GasDensity", "Lb_ft3")
add_parameter("yg",  "Sgg", "Aqui Neylith")
add_parameter("pb",  "psia", "Aqui Neylith")
add_parameter("t",  "Rankine", "Aqui Neylith")
add_parameter("p",  "psia", "Aqui Neylith")
add_parameter("z",  "ZFactor", "Aqui Neylith")
add_author("Standard Equation")
add_db("The calculation is based on the Real Gas Law.")
add_ref("takacs:2005")
add_ref("banzer:1996")
add_internal_note("The equation was verified by using a secondary reference: Bánzer (1996). Date: September 28 2016.")
end_correlation()
