begin_correlation("Pg", "GasDensity", "Lb_ft3")
add_parameter("yg",  "Sgg", "Aqui Neylith")
add_parameter("pb",  "psia", "Aqui Neylith")
add_parameter("t",  "Rankine", "Aqui Neylith")
add_parameter("p",  "psia", "Aqui Neylith")
add_parameter("z",  "ZFactor", "Aqui Neylith")
add_author("Real Gas Law")
end_correlation()
